dashboard/urls/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('upload/', views.uploadData, name='upload'),
    path('export/', views.ExportData, name='export'),
    path('cleardata/', views.clear_data, name='cleardata'),
    path('upload-shapefile/', views.ShapefileUpload, name='upload-shapefile'),
    path('bulk-upload/', views.bulkCreate, name='bulk-upload'),
    # path('clear-data/', views.deleteallfivewdata, name='clear-data'),
    # path('invitation/', views.Invitation, name='invitation'),
    path('login-test/', views.login_test, name='login-test'),
    # path('login-test/<int:group>/<int:partner>', views.login_test, name='login-test'),
    path('logout/', auth_views.LogoutView.as_view(),
         {'next_page': '/dashboard/login/'}, name='logout'),
    path('signup/<int:group>/<int:partner>', views.signup, name='signup'),
    path('createuser', views.createuser, name='createuser'),
    path('updateuser/<int:id>', views.updateuser, name='updateuser'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('check-login/', views.check_login, name='check-login'),
    path('token/', views.auth, name='token'),
    path('main/', views.Dashboard.as_view(), name='main'),
    path('page_province/', views.province_list, name='page_province'),
    path('program-list/', views.ProgramList.as_view(), name='program-list'),
    path('program-add/', views.ProgramCreate.as_view(), name='program-add'),
    path('program-edit/<int:pk>', views.ProgramUpdate.as_view(), name='program-edit'),
    path('program-delete/<int:pk>',
         views.ProgramDelete.as_view(), name='program-delete'),
    path('partner-list/', views.PartnerList.as_view(), name='partner-list'),
    path('partner-add/', views.PartnerCreate.as_view(), name='partner-add'),
    path('partner-edit/<int:pk>', views.PartnerUpdate.as_view(), name='partner-edit'),
    path('partner-delete/<int:pk>',
         views.PartnerDelete.as_view(), name='partner-delete'),
    path('user-delete/<int:pk>', views.UserDelete.as_view(), name='user-delete'),
    path('five-delete/<int:pk>', views.FiveDelete.as_view(), name='five-delete'),
    path('partner-contact-list', views.PartnerContactList.as_view(),
         name='partner-contact-list'),
    path('partner-contact-add/<int:id>',
         views.AddPartnerContact, name='partner-contact-add'),
    path('partner-contact-edit/<int:pk>',
         views.PartnerContactUpdate.as_view(), name='partner-contact-edit'),
    path('partner-contact-delete/<int:pk>',
         views.PartnerContactDelete.as_view(), name='partner-contact-delete'),
    path('sector-list/', views.SectorList.as_view(), name='sector-list'),
    path('sector-add/', views.SectorCreate.as_view(), name='sector-add'),
    path('sector-edit/<int:pk>', views.SectorUpdate.as_view(), name='sector-edit'),
    path('sector-delete/<int:pk>',
         views.SectorDelete.as_view(), name='sector-delete'),
    path('subsector-list/', views.SubSectorList.as_view(), name='subsector-list'),
    path('subsector-add/', views.SubSectorCreate.as_view(), name='subsector-add'),
    path('subsector-edit/<int:pk>',
         views.SubSectorUpdate.as_view(), name='subsector-edit'),
    path('subsector-delete/<int:pk>',
         views.SubSectorDelete.as_view(), name='subsector-delete'),
    path('marker-list/', views.MarkerList.as_view(), name='marker-list'),
    path('marker-cat-add/', views.MarkerCategoryCreate.as_view(),
         name='marker-cat-add'),
    path('marker-cat-edit/<int:pk>',
         views.MarkerCategoryUpdate.as_view(), name='marker-cat-edit'),
    path('marker-cat-delete/<int:pk>',
         views.MarkerCategoryDelete.as_view(), name='marker-cat-delete'),
    path('markervalue-list/', views.MarkerValueList.as_view(),
         name='markervalue-list'),
    path('markervalue-add/', views.MarkerValueCreate.as_view(),
         name='markervalue-add'),
    path('markervalue-edit/<int:pk>',
         views.MarkerValueUpdate.as_view(), name='markervalue-edit'),
    path('markervalue-delete/<int:pk>',
         views.MarkerValueDelete.as_view(), name='markervalue-delete'),
    path('indicator-list/', views.IndicatorList.as_view(), name='indicator-list'),
    path('feedback-list/', views.FeedbackList.as_view(), name='feedback-list'),
    path('faq-list/', views.FAQList.as_view(), name='faq-list'),
    path('tac-list/', views.TACList.as_view(), name='tac-list'),
    path('indicator-add/', views.IndicatorCreate.as_view(), name='indicator-add'),
    path('indicator-edit/<int:pk>',
         views.IndicatorUpdate.as_view(), name='indicator-edit'),
    path('indicator-delete/<int:pk>',
         views.IndicatorDelete.as_view(), name='indicator-delete'),
    path('indicator-data/', views.IndicatorValueList.as_view(),
         name='indicator-data'),
    # path('program-list/', views.ProgramList.as_view(), name='program-list'),
    path('gis-layer-list/', views.GisLayerList.as_view(), name='gis-layer-list'),
    path('layer-add/', views.gisLayer_create, name='layer-add'),
    path('gis-edit/<int:pk>', views.GisLayerUpdate.as_view(), name='gis-edit'),
    path('gis-replace/<int:pk>', views.gisLayer_replace, name='gis-replace'),
    path('gis-delete/<int:pk>', views.gisLayer_delete, name='gis-delete'),
    path('province-list/', views.ProvinceList.as_view(), name='province-list'),
    path('province-add/', views.ProvinceCreate.as_view(), name='province-add'),
    path('province-edit/<int:pk>',
         views.ProvinceUpdate.as_view(), name='province-edit'),
    path('province-delete/<int:pk>',
         views.ProvinceDelete.as_view(), name='province-delete'),
    path('district-list/', views.DistrictList.as_view(), name='district-list'),
    path('district-add/', views.DistrictCreate.as_view(), name='district-add'),
    path('district-edit/<int:pk>',
         views.DistrictUpdate.as_view(), name='district-edit'),
    path('palika-edit/<int:pk>', views.PalilkaUpdate.as_view(), name='palika-edit'),
    path('district-delete/<int:pk>',
         views.DistrictDelete.as_view(), name='district-delete'),
    path('palika-list/', views.PalikaList.as_view(), name='palika-list'),
    path('palika-add/', views.PalilkaCreate.as_view(), name='palika-add'),
    path('palika-delete/<int:pk>',
         views.PalikaDelete.as_view(), name='palika-delete'),
    path('user-list/', views.UserList.as_view(), name='user-list'),
    path('activate/<int:id>', views.activate_user, name='activate'),
    path('status/<int:id>', views.feedback_status, name='feedback-status'),
    path('assign-role/<int:id>', views.assign_role, name='assign-role'),
    path('project-list/', views.ProjectList.as_view(), name='project-list'),
    path('project-add/', views.ProjectCreate.as_view(), name='project-add'),
    path('project-edit/<int:pk>', views.ProjectUpdate.as_view(), name='project-edit'),
    path('project-delete/<int:pk>',
         views.ProjectDelete.as_view(), name='project-delete'),
    path('permission-list/', views.PermissionList.as_view(), name='permission-list'),
    path('permission-add/', views.PermissionCreate.as_view(), name='permission-add'),
    path('permission-edit/<int:pk>',
         views.PermissionUpdate.as_view(), name='permission-edit'),
    path('permission-delete/<int:pk>',
         views.PermissionDelete.as_view(), name='permission-delete'),
    path('five-list/', views.FiveList.as_view(), name='five-list'),
    path('five-add/', views.FiveCreate.as_view(), name='five-add'),
    path('five-edit/<int:pk>', views.FiveUpdate.as_view(), name='five-edit'),
    path('output-list/', views.OutputList.as_view(), name='output-list'),
    path('output-add/', views.OutputCreate.as_view(), name='output-add'),
    path('output-edit/<int:pk>', views.OutputUpdate.as_view(), name='output-edit'),
    path('role-list/', views.RoleList.as_view(), name='role-list'),
    path('create-role/', views.RoleCreate.as_view(), name='create-role'),
    # path('create-role/', views.create_role, name='create-role'),
    path('role-delete/<int:pk>', views.RoleDelete.as_view(), name='role-delete'),
    path('faq-delete/<int:pk>', views.FAQDelete.as_view(), name='faq-delete'),
    path('tac-delete/<int:pk>', views.TACDelete.as_view(), name='tac-delete'),
    # path('role-edit/', views.edit_role, name='role-edit'),
    path('role-edit/<int:pk>', views.RoleUpdate.as_view(), name='role-edit'),

    path('budget-list/', views.BudgetList.as_view(), name='budget-list'),
    path('budget-add/', views.BudgetCreate.as_view(), name='budget-add'),
    path('budget-edit/<int:pk>', views.BudgetUpdate.as_view(), name='budget-edit'),
    path('budget-delete/<int:pk>',
         views.BudgetDelete.as_view(), name='budget-delete'),

    path('cmp-list/', views.CmpList.as_view(), name='cmp-list'),
    path('cmp-add/', views.CmpCreate.as_view(), name='cmp-add'),
    path('cmp-edit/<int:pk>', views.CmpUpdate.as_view(), name='cmp-edit'),
    path('cmp-delete/<int:pk>', views.CmpDelete.as_view(), name='cmp-delete'),

    path('vector-map/', views.VectorMap.as_view(), name='vector-map'),

#     path('gis_style_layer_list/<int:pk>',
#          views.StyleList.as_view(), name='style-list'),
#     path('gis_style_layer_add/<int:pk>',
#          views.StyleCreate.as_view(), name='style-create'),
#     path('gis_style_layer_edit/<int:pk>',
#          views.StyleUpdate.as_view(), name='style-update'),
    
    path('faq-edit/<int:pk>', views.FAQUpdate.as_view(), name='faq-update'),
    path('tac-edit/<int:pk>', views.TACUpdate.as_view(), name='tac-update'),
    path('faq-add', views.FAQCreate.as_view(), name='faq-create'),
    path('tac-add', views.TACCreate.as_view(), name='tac-create'),
    path('ns-list/', views.NSList.as_view(), name='ns-list'),
    path('ns-edit/<int:pk>', views.NSUpdate.as_view(), name='ns-edit'),
    path('manual-list/', views.ManualList.as_view(), name='manual-list'),

dvs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.contrib.auth import views as auth_views
from drf_yasg.generators import OpenAPISchemaGenerator
import debug_toolbar


class BothHttpAndHttpsSchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, request=None, public=False):
        schema = super().get_schema(request, public)
        schema.schemes = ["http", "https"]
        return schema


schema_view = get_schema_view(
    openapi.Info(
        title="Dvs Api Doc",
        default_version='v1',
    ),
    generator_class=BothHttpAndHttpsSchemaGenerator,    
)

urlpatterns = [

    path('admin/', admin.site.urls),
    # path('swagger/', schema_view.with_ui('swagger',
    #      cache_timeout=0), name='schema-swagger-ui'),
    path('api/v1/core/', include('core.urls')),
    path('api/v1/covid/', include('covid.urls')),
    path('dashboard/', include('dashboard.urls.urls')),
    path('api/v2/dashboard/', include('dashboard.urls.dashboard_urls')),

    path('federal/', include('federal.urls')),
    path('api/v1/about_us/', include('about_us.urls')),


    path('', auth_views.LoginView.as_view(), name='login'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
        path(
            "api/docs/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    ]

dashboard/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
import os.path
from io import BytesIO
from PIL import Image
from core.models import Partner, Program, Project


# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300, null=True, blank=True)
    email = models.CharField(max_length=300, null=True, blank=True)
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, related_name='ProfilePartner', null=True, blank=True)
    program = models.ForeignKey(Program, on_delete=models.CASCADE, related_name='ProfileProgram', null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='ProfileProject', null=True, blank=True)
    image = models.FileField(upload_to='upload/profile/', null=True, blank=True)
    thumbnail = models.FileField(upload_to='upload/profile/', editable=False, null=True, blank=True)

    def make_thumbnail(self):
        try:
            image = Image.open(self.image)
            image.thumbnail((200, 150), Image.ANTIALIAS)
            thumb_name, thumb_extension = os.path.splitext(self.image.name)
            thumb_extension = thumb_extension.lower()
            thumb_filename = thumb_name + '_thumb' + thumb_extension
            if thumb_extension in ['.jpg', '.jpeg']:
                FTYPE = 'JPEG'
            elif thumb_extension == '.gif':
                FTYPE = 'GIF'
            elif thumb_extension == '.png':
                FTYPE = 'PNG'
            else:
                return False  # Unrecognized file type
            # Save thumbnail to in-memory file as StringIO
            temp_thumb = BytesIO()
            image.save(temp_thumb, FTYPE)
            temp_thumb.seek(0)
            # set save=False, otherwise it will run in an infinite loop
            self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
            temp_thumb.close()
            return True
        except:
            return False

    def save(self, *args, **kwargs):
        if self.make_thumbnail():
            super(UserProfile, self).save(*args, **kwargs)
        else:
            self.thumbnail = None
            super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username


class Log(models.Model):
    message = models.CharField(max_length=300, null=True, blank=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='UserProfile', null=True, blank=True)
    type = models.CharField(max_length=300, null=True, blank=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.message

federal/models.py
from django.contrib.gis.db import models
from rest_framework_mvt.managers import MVTManager


class ProvinceBoundary(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    code = models.CharField(max_length=100, null=True, blank=True)
    geom = models.MultiPolygonField(srid=4326, null=True)
    objects = models.Manager()
    vector_tiles = MVTManager()

    def __str__(self):
        return self.name


class DistrictBoundary(models.Model):
    province_id = models.ForeignKey(
        ProvinceBoundary,
        on_delete=models.CASCADE,
        related_name="DProvince",
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=100, null=True, blank=True)
    code = models.CharField(max_length=100, null=True, blank=True)
    n_code = models.IntegerField(null=True, blank=True)
    geom = models.MultiPolygonField(srid=4326, null=True)
    objects = models.Manager()
    vector_tiles = MVTManager()

    def __str__(self):
        return self.name


class GapaNapaBoundary(models.Model):
    province_id = models.ForeignKey(
        ProvinceBoundary,
        on_delete=models.CASCADE,
        related_name="Province",
        null=True,
        blank=True,
    )
    district_id = models.ForeignKey(
        DistrictBoundary,
        on_delete=models.CASCADE,
        related_name="District",
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=100, null=True, blank=True)
    cbs_code = models.CharField(max_length=100, null=True, blank=True)
    hlcit_code = models.CharField(max_length=100, null=True, blank=True)
    p_code = models.CharField(max_length=100, null=True, blank=True)
    code = models.IntegerField(null=True, blank=True)
    geom = models.MultiPolygonField(srid=4326, null=True)
    objects = models.Manager()
    vector_tiles = MVTManager()

    def __str__(self):
        return self.name

dashboard/templates/confirm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="dfid-main">
    <!-- dfid breadcrumb -->
    <div class="dfid-breadcrumb pdt-100">
        <ul class="flex-start">
            <li>
                <a href="/dashboard/five-list/"><i class="material-icons">assignment</i> Five W</a>
            </li>
            <li>Data Clear</li>
        </ul>
    </div>
        {% if messages %}
        {% for messages in messages %}
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong></strong> {{messages}}
        </div>
        {% endfor %}
        {% endif %}
    <!-- program form -->
    <form class="program-form" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.name|title }} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <li>Are You Sure you want to delete all your data??</li>

        <div class="form-group">
            <button type="submit" class="dfid-button sm-button">Confirm</button>
        </div>

        </div>


        <!-- category form -->


    </form>
</main>

{% endblock %}

dashboard/templates/created_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="dfid-main">


    <h4> User Created</h4>
        <p> {{ user }} was successfully created , Please contact admin to activate your account  </p>

            </div>


</main>
{% endblock %}

dashboard/templates/palika_add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="dfid-main">
    <!-- dfid breadcrumb -->
    <div class="dfid-breadcrumb pdt-100">
        <ul class="flex-start">
            <li>
                <a href="#"><i class="material-icons">assignment</i> District</a>
            </li>
            <li>New</li>
        </ul>
    </div>
    <!-- program form -->
    <form class="program-form" method="POST">

        {% csrf_token %}

        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.name|title }} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}


        <div class="default-form">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_province_id">Select Province</label>
                        <select name="province_id" id="id_province_id" class="custom-select" required>
                            <option value="" selected disabled>----Select Province----</option>
                            {% for i in province %}

                            <option value="{{i.id}}">{{i.name}}</option>


                            {% endfor %}

                        </select>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_district_id">Select District</label>
                        <select name="district_id" id="id_district_id" class="custom-select" required>
                            <option value="" selected disabled>----Select District----</option>
                            {% for i in district %}

                            <option value="{{i.id}}" valId='{{i.province_id__id}}'>{{i.name}}</option>


                            {% endfor %}

                        </select>
                    </div>

                </div>

            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group ">
                        <label for="id_name" class="">Name</label>
                        <input type="text" class="form-control" name="name" maxlength="100" id="id_name"
                               placeholder="Name" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>


            </div>

            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="id_gn_type_np">Palika Type(np)</label>
                        <select name="gn_type_np" id="id_gn_type_np" class="custom-select" required>

                            <option value="Development area">Development area</option>

                            <option value="Gaunpalika" selected>Gaunpalika</option>

                            <option value="Hunting reserve">Hunting reserve</option>

                            <option value="Nagarpalika">Nagarpalika</option>

                            <option value="Mahanagarpalika">Mahanagarpalika</option>

                            <option value="Upamahanagarpalika">Upamahanagarpalika</option>

                            <option value="Wildlife reserve">Wildlife reserve</option>

                            <option value="Watershed and wildlife reserve">Watershed and wildlife reserve</option>

                        </select>
                    </div>

                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="id_gn_type_en">Palika Type(en)</label>
                        <select name="gn_type_en" id="id_gn_type_en" class="custom-select" required>
                            <option value="Rural municipality" selected>Rural municipality</option>

                            <option value="Urban municipality">Urban municipality</option>

                            <option value="Designated area">Designated area</option>

                            <option value="Sub metropolitan">Sub metropolitan</option>

                            <option value="Metropolitan">Metropolitan</option>

                        </select>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label for="id_geography">Geography</label>
                        <select name="geography" id="id_geography" class="custom-select" required>
                            <option value="Terai" selected>Terai</option>

                            <option value="Hill">Hill</option>

                            <option value="Shivalik">Shivalik</option>

                            <option value="Mountain">Mountain</option>

                            <option value="High Mountain">High Mountain</option>

                        </select>
                    </div>

                </div>

            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group ">
                        <label for="id_population" class="">Population</label>
                        <input type="text" class="form-control" name="population" step="any" id="id_population"
                               placeholder="1133434" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>
            </div>


            <div class="row">

                <div class="col-md-4">
                    <div class="form-group ">
                        <label for="id_cbs_code" class="">Cbs Code</label>
                        <input type="text" class="form-control" name="cbs_code" maxlength="100"
                               id="id_cbs_code"
                               placeholder="123" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group ">
                        <label for="id_hlcit_code" class="">Hlcit Code</label>
                        <input type="text" class="form-control" name="hlcit_code" maxlength="100"
                               id="id_hlcit_code"
                               placeholder="84349" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group ">
                        <label for="id_p_code" class="">P Code</label>
                        <input type="text" class="form-control" name="p_code" maxlength="100" id="id_p_code"
                               placeholder="84349" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>


            </div>


            <div class="form-group mrt-100">
                <button type="submit" class="dfid-button sm-button">Save</button>
            </div>

        </div>


        <!-- category form -->


    </form>
</main>

{% endblock %}
{% block five_add %}
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
        $('#id_province_id').change(function(e) {
            e.preventDefault();
            changefunction($(this).val(), '#id_district_id option')
        });
    });
</script>
{% endblock %}

dashboard/templates/program_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="dfid-main">


    <h4>Program Delete</h4>
    <form method="post" class="program-form">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?


        <div class="row">
            <div class="form-group mrt-100 col-md-1">
                <button type="submit" value="Submit" class="dfid-button sm-button">Yes</button>
            </div>

            <div class="form-group mrt-100 ">
                <a href="/dashboard/program-list ">
                    <button type="button" class="dfid-button  sm-button">No</button>
                </a>
            </div>

        </div>
    </form>

</main>
{% endblock %}

dashboard/templates/sub_sector_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="dfid-main">
    <!-- dfid breadcrumb -->
    <div class="dfid-breadcrumb pdt-100">
        <ul class="flex-start">
            <li>
                <a href="/dashboard/subsector-list/"><i class="material-icons">assignment</i>Sub Sector</a>
            </li>
            <li>Edit</li>
        </ul>
    </div>
    <!-- program form -->
    <form class="program-form" method="POST">

        {% csrf_token %}

        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.name|title }} {{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}

        <div class="default-form">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_sector_id">Select Sector</label>
                        <select name="sector_id" id="id_sector_id" class="custom-select" required>

                            {% for sector in sectors %}


                            {% if form.instance.sector_id.id == sector.id %}

                            <option value="{{sector.id}}" selected>{{sector.name}}</option>

                            {% else %}

                            <option value="{{sector.id}}">{{sector.name}}</option>

                            {% endif %}

                            {% endfor %}

                        </select>
                    </div>

                </div>


            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group ">
                        <label for="id_name" class="">Name</label>
                        <input type="text" class="form-control" name="name" maxlength="100" id="id_name"
                               placeholder="Name" value="{{ form.instance.name }}" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group ">
                        <label for="id_code" class="">Code</label>
                        <input type="text" class="form-control" name="code" maxlength="100" id="id_code"
                               placeholder="84349" value="{{ form.instance.code }}" required/>
                        <!--                        <span class="error-message"><i class="material-icons error-icon">error_outline</i>-->
                        <!--                                        Please ennter name</span>-->
                    </div>
                </div>

            </div>


            <div class="form-group mrt-100">
                <button type="submit" class="dfid-button sm-button">Save</button>
            </div>

        </div>


        <!-- category form -->


    </form>
</main>

{% endblock %}